name: CI

on:
  push:
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install MoonBit
        run: curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
      - name: Add MoonBit to PATH
        run: echo "$HOME/.moon/bin" >> $GITHUB_PATH
      - name: Moon Info
        run: moon info
      - name: Moon Check
        run: moon check
      - name: Moon Format Check
        run: moon fmt --check
      - name: Moon Test
        run: moon test
